### ISSUE TITLE
Tools hang on Windows

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#16]
**Describe the feature you would like**
Is it possible to add a bin to soft converter?

**Additional context**
Also how do I operate the VCDU to CADU converter? 

Thank you so much!!

**Comment by Xerbo** [comment]
The vcdu2cadu tool is only available when building from source as of now since I have not added it to the workflows yet. Actually using it is as simple as `./vcdu2cadu input.vcdu output.cadu`/

As for bin to soft that doesn't really make sense as it is going *down* a processing level, it would make more sense for a bin2raw16/bin2cadu tool.

**Comment by zeke800** [comment]
Ok, thank you so much!! I assume the tools are added to the Windows build now? Thank you so much for vigilantly responding to all my issues!

**Comment by zeke800** [comment]
Just tested, it's fine! Thank you so much!

**Comment by zeke800** [comment]
Hmm... It's just hanging? 
![cadu](https://user-images.githubusercontent.com/82127189/157506719-bf5d2d5c-dbc6-4008-8522-dd78bc53f7a3.png)

**Comment by zeke800** [comment]
Yayy!! I was able to decode using SatDump :) 
![MSU-MR-5-EQU-PROJ](https://i.ibb.co/ZLyHNJy/MSU-MR-RGB-221-CORRECTED.png)

**Comment by zeke800** [comment]
I have found that while Meteor decodes fine, it does not write NOAA CADUs. The size is just 0 bytes.

**Comment by Xerbo** [comment]
NOAA doesn't use CADUs, use the bin2raw16 tool

**Comment by zeke800** [comment]
Ohhhhh!!! Why didn't I think of that XD
