### ISSUE TITLE
Add other instruments

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#7]
**Describe the feature you would like**
Decode other instruments from HRPT data (e.g. AMSU , HRIS, TIP frames, timestamps, possibly location data?). 

**Additional context**

**Comment by Xerbo** [comment]
MHS is already supported so adding support for AMSU and/or HIRS shouldn't be too much work as their format is pretty similar. The reason why I haven't done this yet is because the data doesn't have much use without a lot of processing.

TIP/AIP frames are already decoded intermediately (but with no way of exporting, maybe have an export button for use in other software?). And as for timestamps/positions thats already done and is used for georeferencing.

**Comment by zeke800** [comment]
Yes, I think that it would be very useful to export complete HRPT data mainly because one may create some great composites with it. May I suggest looking into a style similar to satdump. It outputs (to the folder of your choice) folders containing the data, all labeled nicely. I think that this format will play very well with LeanHRPT-Decode. 

Thanks :)

**Comment by zeke800** [comment]
Also on Meteor there are more instruments such as the galactic ray mapper. It would be very useful (scientifically) to be able to analyze this data.

**Comment by Xerbo** [comment]
> Yes, I think that it would be very useful to export complete HRPT data mainly because one may create some great composites with it. May I suggest looking into a style similar to satdump. It outputs (to the folder of your choice) folders containing the data, all labeled nicely. I think that this format will play very well with LeanHRPT-Decode.

A very similar feature is implemented via [the command line interface](https://github.com/Xerbo/LeanHRPT-Decode/wiki/Command-Line), which is only missing minor functionality like projection and map overlays.

**Comment by zeke800** [comment]
Thanks! I didn't know that the command line provided that functionality. Still, it would be very nice to have all the other instruments decoded :) 

I have little experience writing decoders, though I wrote 2 of my own protocols. I can try to contribute, especially given that you said that it will be easy because MHS is already decoded. The only problem - I have absolutely no idea how HRPT is encoded :( Is there any document about different satellite's HRPT downlink and it's structure? How did you write this decoder so far? :) 

Thanks!

**Comment by Xerbo** [comment]
Ive compiled a list of various sounders and some basic info on them:

- MWHS - has an odd quirk (broadcasts a, what looks like, ring buffer) but simple
- AMSU - seems simple at a first glance (although some weirdness on MetOp)
- MTVZA - not much info on this, though guessing by the packet size I'm guessing it transmits a single pixel per packet
- HIRS - dead on MetOp-B, not on MetOp-C, looks very painful on NOAA

AMSU on NOAA seems like a good starting point since all the AIP code is already in place and it's [well documented](https://archive.org/details/noaa-klm-guide).

**Comment by zeke800** [comment]
Hi! Thank you so much for digging up that guide :) On what page does it mention the AMSU data format (there are over 2500 pages)? Also, I believe [this](https://github.com/altillimity/L-Band-Decoders) repository has a decoder for MTVZA as well as a large portion of the other sounders.

Thanks!

**Comment by Xerbo** [comment]
The sections of interest are 4.1.4.1 (AMSU format) and 4.1.5.2 (AIP format)

**Comment by Xerbo** [comment]
I've added both (NOAA) HIRS and MTVZA support.

**Comment by Xerbo** [comment]
NOAA AMSU-A added in 85cc7c7
